Example/Example1/blog/urls.py
"""example1 URL Configuration

"""

from django.conf.urls import url
from django.contrib import admin
from .feeds import LatestPostsFeed

from Example.Example1.blog import views

app_name = "blog"
urlpatterns = [
    url(r"^$", views.post_list, name="post_list"),
    # url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r"^tag/(?P<tag_slug>[-\w]+)/$", views.post_list, name="post_list_by_tag"),
    url(r"^(?P<post_id>\d+)/share/$", views.post_share, name="post_share"),
    url(
        r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/" r"(?P<post>[-\w]+)/$",
        views.post_detail,
        name="post_detail",
    ),
    url(r"^feed/$", LatestPostsFeed(), name="post_feed"),
]

Example/Example1/blog_setings/urls.py
from Example.Example1.blog.sitemaps import PostSitemap
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^blog/", include("blog.urls")),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

Example/Example1/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        to=User, on_delete=models.PROTECT, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.strftime("%m"),
                self.publish.strftime("%d"),
                self.slug,
            ],
        )

    # eg Post.published.filter(title__startwith='dupa')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT, related_name="comments")
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Comment added by {} for post {}".format(self.name, self.post)

Example/Example1/blog/forms.py
from django import forms

from Example.Example1.blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

Example/Example1/blog/views.py
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from taggit.models import Tag

from Example.Example1.blog.forms import EmailPostForm, CommentForm
from Example.Example1.blog.models import Post, Comment


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 5)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)

    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request, "blog/post/list.html", {"page": page, "posts": posts, "tag": tag}
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    comments = post.comments.filter(active=True)
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = CommentForm()

    else:
        comment_form = CommentForm()
    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "comment_form": comment_form,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) Read: "{}"'.format(cd["name"], cd["email"], post.title)
            message = 'Read post: "{} on page {}\n\n comment added bt {}: {}'.format(
                post.title, post_url, cd["name"], cd["comments"]
            )
            send_mail(subject, message, "testaccouny123321@gmail.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


class PostListView(ListView):  # same as post_list
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 5
    template_name = "blog/post/list.html"

Example/Example1/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
      <p>This is My blog. Published posts: {% total_posts %}</p>
      <p><a href="{% url "blog:post_feed" %}"> Subscribe RSS</a></p>
    <h3>
      Latest posts
    </h3>
    {% show_latest_posts 5 %}
    <h3>
      Most commented posts
    </h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
    {% for post in most_commented_posts %}
      <li>
        <a href = "{{ post.get_absolute_url }}"> {{ post.title }}</a>
      </li>
      {% endfor %}
     </ul>
  </div>
</body>
</html>

Example/Example1/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{post.title}} {% endblock %}
{% block content %}

<h1 id="title">
    {{ post.title }}
</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
<p class="tags">Tags :
    {% for tag in post.tags.all %}
    <a href= "{% url "blog:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% if not forloop.last %},{% endif %}
    {% endfor %}
</p>

<div id="postContent"> {{ post.body | linebreaks }}</div>

<p id="share_post">
    <a href = "{%url "blog:post_share" post.id %}">Share post
    </a>
</p>

<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{post.title}}
    </a>
</p>
{% empty %}
There is no similar posts
{% endfor %}


{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} Comment{{ total_comments|pluralize:"s" }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class = "comment">
    <p class = "info">
        Comment {{ forloop.counter }} added by {{comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body |markdown }}
</div>
{% empty %}
<p>No comments yet.</p>
{% endfor %}
{% if new_comment %}
<h2> Comment was added</h2>
{% else %}
<h2>Add new comment</h2>
<form action = "." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
{% endblock %}

Example/Example1/blog/templates/blog/post/latest_posts.html
<!DOCTYPE html>
<html lang="en">
<ul id="Latest_posts">
    {% for post in latest_posts %}
    <li>
        <a href = "{{ post.get_absolute_url }}" > {{post.title }}</a>
    </li>
    {% endfor %}
</ul>
</html>

Example/Example1/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My blog{% endblock %}
{% block content %}

<h1>My blog</h1>
{% if tag %}
<h2>Post with tag "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}" >
        {{ post.title }}
    </a>
</h2>
<!--<p class="tags">Tags : {{post.tags.all|join:", "}}</p>-->
<p class="tags">Tags :
    {% for tag in post.tags.all %}
    <a href= "{% url "blog:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% if not forloop.last %},{% endif %}
    {% endfor %}
</p>
<p class ="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body | markdown | truncatewords:30 | linebreaks }}
{% endfor %}
{% include "blog/post/pagination.html" with page=posts %}
{% endblock %}

Example/Example1/blog/templates/blog/post/pagination.html
<div class = "pagination" >
    <span class = "step-links">
        {% if page.has_previous %}
        <a href ="?page={{ page.previous_page_number }}" > Previous </a>
        {% endif %}
        <span class = "current">
         Page {{ page.number }} from {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href= "?page={{ page.next_page_number }}" >Next</a>
        {% endif %}
    </span>
 </div>